### ISSUE TITLE
download link for pre-trained weights not working

### ISSUE THREAD

**Issue by rnunziata** [DeepSegment/ConvNet-Segment#1]
download  linkfor pre-trained weights not working
Pre-trained model: VGG16 -> GoogLeNet (inception v3)

**Comment by txzhao** [comment]
Sorry for this download link problem. Now it should be fixed. You can also start your downloads by clicking this link: https://drive.google.com/open?id=0B4wMcSmM_17YelpCVFNaMHktVDQ
