### ISSUE TITLE
your report?

### ISSUE THREAD

**Issue by liuzhisheng1226** [DeepSegment/ConvNet-Segment#12]
I read your report.pdf,But I didn't find any paper in googlenet,Can you send me the paper about this project?

**Comment by txzhao** [comment]
Hi,

Sorry for such a late reply. The paper of GoogLeNet inception can be found here: [https://arxiv.org/abs/1409.4842](url), [https://arxiv.org/abs/1512.00567](url).

Some good materials are also listed as follows as well:
[https://leonardoaraujosantos.gitbooks.io/artificial-inteligence/content/googlenet.html](url)
[https://towardsdatascience.com/neural-network-architectures-156e5bad51ba](url)

Hope these guys could help you!

Cheers,
Tianxiao
